<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Model;

use Magento\Framework\Model\AbstractModel;
use Baytalebaa\Shops\Model\ResourceModel\Subcatalogs\CollectionFactory as SubCatalogCollectionFactory;

class Catalogs extends AbstractModel
{
    protected $subCatalogCollectionFactory;


    public function __construct(
        SubCatalogCollectionFactory $subCatalogCollectionFactory,
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\Registry $registry,
        array $data = []
    ) {
        $this->subCatalogCollectionFactory = $subCatalogCollectionFactory;
        parent::__construct($context, $registry, null, null, $data);
    }
    /**
    * Define resource model
    */
    protected function _construct()
    {
        $this->_init('Baytalebaa\Shops\Model\ResourceModel\Catalogs');
    }

    public function getShopId()
    {
        return $this->getData('Catalog_shop_id');
    }

    public function getTitle()
    {
        return $this->getData('title');
    }

    public function getStatus()
    {
        return $this->getData('status');
    }

    public function getContent()
    {
        return $this->getData('content');
    }

    public function getImage()
    {
        return $this->getData('image');
    }

    /**
    * Define resource relations logic
    */
    //-----------------------------------------------
    // get SubCatalogs form catalog
    public function getSubCatalogs()
    {
        $subCatalogs = $this->subCatalogCollectionFactory->create()
            ->addFieldToFilter('catalog_id', $this->getId())
            ->addFieldToFilter('status', 1); // Optional: Filter by status if needed

        return $subCatalogs;
    }
    // get shop imaeg
    // get shop icon
    //-----------------------------------------------

}