<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Model;

use Magento\Framework\Model\AbstractModel;
use Magento\Catalog\Api\CategoryRepositoryInterface;
use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\CollectionFactory as ProductCollectionFactory;
use Magento\Sales\Model\ResourceModel\Report\Bestsellers\CollectionFactory as BestsellersCollectionFactory;
use Magento\Framework\Exception\NoSuchEntityException;
use Baytalebaa\Shops\Model\ResourceModel\Catalogs\CollectionFactory as CatalogCollectionFactory;
use Magento\Catalog\Model\CategoryFactory;

class Shops extends AbstractModel
{
    protected $categoryRepository;
    protected $productCollectionFactory;
    protected $bestsellersCollectionFactory;
    protected $catalogCollectionFactory;
    private $categoryFactory;

    
    public function __construct(
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\Registry $registry,
        CatalogCollectionFactory $catalogCollectionFactory,
        CategoryRepositoryInterface $categoryRepository,
        CategoryFactory $categoryFactory,
        ProductCollectionFactory $productCollectionFactory,
        BestsellersCollectionFactory $bestsellersCollectionFactory,
        array $data = []
    ) {
        $this->catalogCollectionFactory = $catalogCollectionFactory;
        $this->categoryRepository = $categoryRepository;
        $this->categoryFactory           = $categoryFactory;
        $this->productCollectionFactory = $productCollectionFactory;
        $this->bestsellersCollectionFactory = $bestsellersCollectionFactory;
        parent::__construct($context, $registry, null, null, $data);
    }
    /**
     * Define resource model
     */
    protected function _construct()
    {
        $this->_init('Baytalebaa\Shops\Model\ResourceModel\Shops');
    }

    public function getShopCategoryId()
    {
        return $this->getData('shop_brand_id');
    }

    public function getTitle()
    {
        return $this->getData('title');
    }

    public function getDescription()
    {
        return $this->getData('description');
    }

    public function getStatus()
    {
        return $this->getData('status');
    }

    public function getContent()
    {
        return $this->getData('content');
    }

    public function getCertificationsAndAwards()
    {
        return $this->getData('certifications_and_awards');
    }

    public function getShopOn()
    {
        return $this->getData('shop_on');
    }

    public function getServiceProvided()
    {
        return $this->getData('service_provided');
    }

    public function getAreasCovered()
    {
        return $this->getData('areas_covered');
    }

    public function getIcon()
    {
        return $this->getData('icon');
    }

    public function getImage()
    {
        return $this->getData('image');
    }
    // relations logic
    //-----------------------------------------------    
    /**
    * Get subcategory for shops category
    */
    public function getSubcategories($categoryId)
    {
        try {
            $category = $this->categoryRepository->get($categoryId);
            return $category->getChildrenCategories(); // This will get the child categories
        } catch (NoSuchEntityException $e) {
            return []; // Return an empty array if the category is not found
        }
    }
    /**
    * Get new products for the related category
    */
    public function getRelatedCategoryNewProducts()
    {
        try {
            $category = $this->categoryRepository->get($this->getShopBrandId());
            $productCollection = $this->productCollectionFactory->create();
            $productCollection->addCategoryFilter($category)
                ->addAttributeToSelect(['name', 'price', 'image'])
                ->addAttributeToSort('entity_id', 'DESC')
                ->setPageSize(10);
            return $productCollection;
        } catch (NoSuchEntityException $e) {
            return null;
        }
    }

    /**
    * Get top-selling products for the related category
    */
    /**
 * Get top-selling products for the related category
 */

    public function getRelatedCategoryTopSellingProducts()
    {
        $category = $this->categoryRepository->get($this->getShopBrandId());
        if ($category->getData('is_virtual_category')) {
            $category = $this->categoryFactory->create()->setStoreId(1)->load($this->getShopBrandId());
            $productCollection = $this->productCollectionFactory->create();
            $productCollection->addCategoryFilter($category);
            
            $productCollection->addAttributeToSelect(['name', 'price', 'image']); 

            // Join sales order table to calculate bestseller products
            $productCollection->getSelect()->join(
                ['sales' => $productCollection->getTable('sales_order_item')],
                'e.entity_id = sales.product_id',
                ['ordered_qty' => 'SUM(sales.qty_ordered)']
            );

            // Group by product ID to aggregate sales data
            $productCollection->getSelect()->group('e.entity_id');

            // Order by the number of sales (bestsellers)
            $productCollection->getSelect()->order('ordered_qty DESC');

            $productCollection->setPageSize(10);
            return $productCollection;
          
        } else {
            return [];
        }
    }

    /**
    * Get the Shop catalogs
    */
    public function getShopCatalogs()
    {
        $Catalogs = $this->catalogCollectionFactory->create()
            ->addFieldToFilter('catalog_id', $this->getId())
            ->addFieldToFilter('status', 1); // Optional: Filter by status if needed

        return $Catalogs;
    }
    //-----------------------------------------------
}