<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Block;

use Magento\Framework\View\Element\Template\Context;
use Baytalebaa\Shops\Model\ShopsFactory;
/**
 * Shops List block
 */
class CatalogsListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Shops
     */
    protected $_shops;
    public function __construct(
        Context $context,
        ShopsFactory $shops
    ) {
        $this->_shops = $shops;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Baytalebaa Shops Module List Page'));
        
        if ($this->getShopsCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'baytalebaa.shops.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getShopsCollection()
            );
            $this->setChild('pager', $pager);
            $this->getShopsCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getShopsCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $shops = $this->_shops->create();
        $collection = $shops->getCollection();
        $collection->addFieldToFilter('status','1');
        //$shops->setOrder('shops_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}