<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Catalogs
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Block;
use Magento\Framework\View\Element\Template\Context;
use Baytalebaa\Shops\Model\CatalogsFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Catalogs content block
 */
class Catalogs extends \Magento\Framework\View\Element\Template
{
    /**
    * @var Catalogs
    */
    protected $_catalogs;
    private $_catalogsid = null;

    public function __construct(
        Context $context,
        CatalogsFactory $catalogs,
        FilterProvider $filterProvider
    ) {
        $this->_catalogs = $catalogs;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }
    public function _prepareLayout()
    {
        // $this->pageConfig->getTitle()->set(__('Baytalebaa Catalogs Module'));
        
        return parent::_prepareLayout();
    }
   
    public function getSingleData()
    {
        $_shopid = $this->getRequest()->getParam('shop');
        $_catalogid = $this->getRequest()->getParam('catalog');
        $catalogs = $this->_catalogs->create();
        $singleData = $catalogs->load($_catalogid);
        // echo "0x13v: ".$singleData->getTitle();
        // var_dump($singleData->debug());die;
        if($singleData->getCatalogsId() || $singleData['catalog_id'] && $singleData->getStatus() == 1){
            $this->_catalogsid = $id;
            return $singleData;
        }else{
            return false;
        }
    }

    public function getId()
    {
        return $this->_catalogsid;
    }
}
