<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Block;

use Magento\Framework\View\Element\Template\Context;
use Baytalebaa\Shops\Model\ShopsFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Shops View block
 */
class ShopsView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Shops
     */
    protected $_shops;
    public function __construct(
        Context $context,
        ShopsFactory $shops,
        FilterProvider $filterProvider
    ) {
        $this->_shops = $shops;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Baytalebaa Shops Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $shops = $this->_shops->create();
        $singleData = $shops->load($id);
        if($singleData->getShopsId() || $singleData['shops_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}