<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Catalogs
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Block;
use Magento\Framework\View\Element\Template\Context;
use Baytalebaa\Shops\Model\SubcatalogsFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Catalogs content block
 */
class Subcatalogs extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Subcatalogs
     */
    protected $_subcatalogs;
    public function __construct(
        Context $context,
        SubcatalogsFactory $subcatalogs,
        FilterProvider $filterProvider
    ) {
        $this->_subcatalogs = $subcatalogs;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }
    public function _prepareLayout()
    {
        // $this->pageConfig->getTitle()->set(__('Baytalebaa Catalogs Module'));

        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $_shopid = $this->getRequest()->getParam('shop');
        $_catalogid = $this->getRequest()->getParam('catalog');
        $_subcatalogid = $this->getRequest()->getParam('subcatalog');
        $catalogs = $this->_subcatalogs->create();
        $singleData = $catalogs->load($_subcatalogid);
        if($singleData->getsubCatalogId() || $singleData['subcatalog_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}