<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Block;

use Magento\Framework\View\Element\Template\Context;
use Baytalebaa\Shops\Model\SubcatalogsFactory;
use Magento\Framework\View\Element\Template;

/**
 * Subcatalogs content block
 */
class Subcatalogs extends Template
{

    protected $_subcatalogs;

    public function __construct(
        Context $context,
        SubcatalogsFactory $subcatalogsFactory
    ) {
        $this->_subcatalogs = $subcatalogsFactory;
        parent::__construct($context);
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('shop');
        $subcatalogs = $this->_subcatalogs->create();
        $singleData = $subcatalogs->load($id);
        if($singleData->getShopsId() || $singleData['subcatalog_id'] && $singleData->getStatus() == 1){

            return $singleData;
        }else{
            return false;
        }
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Baytalebaa Subcatalogs Module'));
        
        return parent::_prepareLayout();
    }
}
