<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Block\Adminhtml\Subcatalogs\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Baytalebaa\Shops\Model\ResourceModel\Catalogs\CollectionFactory;

class Main extends Generic implements TabInterface
{
    protected $_wysiwygConfig;
 
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig,
        CollectionFactory $catalogCollectionFactory, // Inject the Shop CollectionFactory
        array $data = []
    ) 
    {
        $this->_wysiwygConfig = $wysiwygConfig;
        $this->_catalogCollectionFactory = $catalogCollectionFactory; // Assign CollectionFactory
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * {@inheritdoc}
     */
    public function getTabLabel()
    {
        return __('Subcatalogs Information');
    }

    /**
     * {@inheritdoc}
     */
    public function getTabTitle()
    {
        return __('Subcatalogs Information');
    }

    /**
     * {@inheritdoc}
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function isHidden()
    {
        return false;
    }

    /**
     * Prepare form before rendering HTML
     *
     * @return $this
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('current_baytalebaa_shops_subcatalogs');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('subcatalogs_');
        $fieldset = $form->addFieldset('base_fieldset', ['legend' => __('Subcatalogs Information')]);
        if ($model->getId()) {
            $fieldset->addField('subcatalog_id', 'hidden', ['name' => 'subcatalog_id']);
        }
        // Modify the Catalog_shop_id to be a select field
        $fieldset->addField(
            'catalog_id',
            'select',
            [
                'name' => 'catalog_id',
                'label' => __('Catalog ID'),
                'title' => __('Catalog ID'),
                'required' => true,
                'values' => $this->_getCatalogOptions()  // Load shop options
            ]
        );
        $fieldset->addField(
            'title',
            'text',
            ['name' => 'title', 'label' => __('Title'), 'title' => __('Title'), 'required' => true]
        );
        $fieldset->addField(
            'url_slug',
            'text',
            ['name' => 'url_slug', 'label' => __('URL Slug'), 'title' => __('URL Slug'), 'required' => true]
        );
        
        // $fieldset->addType('ImageMultible', 'Baytalebaa\Shops\Block\Adminhtml\Subcatalogs\Helper\ImageMultible');
        // $fieldset->addField(
        //     'images',
        //     'ImageMultible',
        //     array(
        //         'name' => 'images[]', // declare this as array. Otherwise only one image will be uploaded
        //         'multiple' => 'multiple', // declare input as 'multiple'
        //         'label' => __('Images'),
        //         'title' => __('Images'),
        //         'required' => true,
        //         'note' => __('Allowed file types: jpg, jpeg, gif, png'),
        //     )
        // );
        $fieldset->addField(
            'related_products',
            'text',
            ['name' => 'related_products', 'label' => __('Related Products'), 'title' => __('Related Products'), 'required' => true]
        );
        $fieldset->addField(
            'image',
            'image',
            [
                'name' => 'image',
                'label' => __('Image'),
                'title' => __('Image'),
                'required'  => false
            ]
        );
        $fieldset->addField(
            'status',
            'select',
            ['name' => 'status', 'label' => __('Status'), 'title' => __('Status'),  'options'   => [0 => 'Disable', 1 => 'Enable'], 'required' => true]
        );
        $fieldset->addField(
            'content',
            'editor',
            [
                'name' => 'content',
                'label' => __('Content'),
                'title' => __('Content'),
                'style' => 'height:26em;',
                'required' => true,
                'config'    => $this->_wysiwygConfig->getConfig(),
                'wysiwyg' => true
            ]
        );       
        $form->setValues($model->getData());
        $this->setForm($form);
        return parent::_prepareForm();
    }

    /**
     * Get shop options for the select field
     *
     * @return array
     */
    protected function _getCatalogOptions()
    {
        $options = [];
        $catalogCollection = $this->_catalogCollectionFactory->create();

        foreach ($catalogCollection as $catalog) {
            $options[] = [
                'value' => $catalog->getId(),
                'label' => $catalog->getTitle()
            ];
        }

        return $options;
    }
}
