<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Model\ResourceModel\SubCatalogs;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'subcatalog_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Baytalebaa\Shops\Model\SubCatalogs',
            'Baytalebaa\Shops\Model\ResourceModel\SubCatalogs'
        );
    }
}