<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Controller\Adminhtml\SubCatalogs;

class Edit extends \Baytalebaa\Shops\Controller\Adminhtml\SubCatalogs
{

    public function execute()
    {
        $id = $this->getRequest()->getParam('id');
        
        $model = $this->_objectManager->create('Baytalebaa\Shops\Model\SubCatalogs');

        if ($id) {
            $model->load($id);
            if (!$model->getId()) {
                $this->messageManager->addError(__('This SubCatalogs no longer exists.'));
                $this->_redirect('baytalebaa_shops/*');
                return;
            }
        }
        // set entered data if was error when we do save
        $data = $this->_objectManager->get('Magento\Backend\Model\Session')->getPageData(true);
        if (!empty($data)) {
            $model->addData($data);
        }
        $this->_coreRegistry->register('current_baytalebaa_shops_subCatalogs', $model);
        $this->_initAction();
        $this->_view->getLayout()->getBlock('shops_subCatalogs_edit');
        $this->_view->renderLayout();
    }
}
