<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Controller\Adminhtml\Subcatalogs;

class Index extends \Baytalebaa\Shops\Controller\Adminhtml\Subcatalogs
{
    /**
     * shop list.
     *
     * @return \Magento\Backend\Model\View\Result\Page
     */
    public function execute()
    {
        /** @var \Magento\Backend\Model\View\Result\Page $resultPage */
        $resultPage = $this->resultPageFactory->create();        
        $resultPage->setActiveMenu('Baytalebaa_Shops::subcatalog');
        $resultPage->getConfig()->getTitle()->prepend(__('Subcatalogs Items'));
        $resultPage->addBreadcrumb(__('Subcatalogs'), __('Subcatalogs'));
        $resultPage->addBreadcrumb(__('Items'), __('Items'));
        return $resultPage;
    }
}