<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Setup;

use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;

/**
 * @codeCoverageIgnore
 */
class InstallSchema implements InstallSchemaInterface
{
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
		$installer = $setup;
		$installer->startSetup();

		/**
		 * Creating table baytalebaa_shops
		 */
		if (!$installer->tableExists('baytalebaa_shops')) {
			$table = $installer->getConnection()->newTable(
				$installer->getTable('baytalebaa_shops')
			)->addColumn(
				'shops_id',
				\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
				null,
				['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
				'Entity Id'
			)->addColumn(
				'brand_id',
				\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
				null,
				['nullable' => true, 'unsigned' => true],
				'Shop brand ID'
			)->addColumn(
				'title',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				255,
				['nullable' => true],
				'Title'
			)->addColumn(
				'description',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				255,
				['nullable' => true,'default' => null],
				'Description'
			)->addColumn(
				'status',
				\Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
				1,
				['nullable' => false,'default' => 0],
				'Status'
			)->addColumn(
				'content',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				'2M',
				['nullable' => true,'default' => null],
				'Content'
			)->addColumn(
				'certifications_and_awards',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				'2M',
				['nullable' => true,'default' => null],
				'Certifications and Awards'
			)->addColumn(
				'shop_on',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				'2M',
				['nullable' => true,'default' => null],
				'Shop On Bayt Alebaa'
			)->addColumn(
				'service_provided',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				'2M',
				['nullable' => true,'default' => null],
				'Service Provided'
			)->addColumn(
				'areas_covered',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				'2M',
				['nullable' => true,'default' => null],
				'Areas Covered'
			)->addColumn(
				'icon',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				255,
				['nullable' => true,'default' => null],
				'icon'
			)->addColumn(
				'image',
				\Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
				255,
				['nullable' => true,'default' => null],
				'Image'
			)->addColumn(
				'created_at',
				\Magento\Framework\DB\Ddl\Table::TYPE_TIMESTAMP,
				null,
				['nullable' => false],
				'Created At'
			)->addForeignKey(
				$installer->getFkName(
					'baytalebaa_shops', 
					'brand_id', 
					'mgs_brand', 
					'brand_id'
				),
				'brand_id',
				$installer->getTable('baytalebaa_shops'),
				'brand_id',
				\Magento\Framework\DB\Ddl\Table::ACTION_CASCADE
			)->setComment(
				'Baytalebaa Shops Table'
			);
			$installer->getConnection()->createTable($table);
		}
		$installer->endSetup();
	}
}