<?php
/**
 * @category   Baytalebaa
 * @package    Baytalebaa_Shops
 * @author     m.ashraf@baytalebaa.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Baytalebaa\Shops\Controller\Index;

use Magento\Framework\App\Action\Context;
use Magento\Framework\Exception\NotFoundException;
use Baytalebaa\Shops\Block\ShopsView;

class View extends \Magento\Framework\App\Action\Action
{
	protected $_shopsview;

	public function __construct(
        Context $context,
        ShopsView $shopsview
    ) {
        $this->_shopsview = $shopsview;
        parent::__construct($context);
    }

	public function execute()
    {
    	if(!$this->_shopsview->getSingleData()){
    		throw new NotFoundException(__('Parameter is incorrect.'));
    	}
    	
        $this->_view->loadLayout();
        $this->_view->getLayout()->initMessages();
        $this->_view->renderLayout();
    }
}
